project:
  type: website

website:
  title: Mitchell O'Hara-Wild
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
