project:
  type: website

website:
  title: Mitchell O'Hara-Wild
  description: "Personal website and blog of Mitchell O'Hara-Wild"
  site-url: "https://mitchelloharawild.com/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-after-body: plausible.html